# Copyright 2026 Ian Pike
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Turning one compiled shader into a header the utility target compiles in.
#
# Script mode only, run from a custom command:
#     cmake -DIN=<binary> -DOUT=<header> -DSYMBOL=<identifier> -P cmake/azoth_rhi_embed_shader.cmake
#
# Shaders are compiled at build time, not checked in as bytecode, so this runs on every build that
# changed the source and never on a clean tree.

if(NOT DEFINED IN OR NOT DEFINED OUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "azoth_rhi_embed_shader: pass -DIN=, -DOUT= and -DSYMBOL=.")
endif()

if(NOT EXISTS "${IN}")
    message(FATAL_ERROR "azoth_rhi_embed_shader: ${IN} does not exist. The shader compile step did not produce it.")
endif()

# Defaulted, so a caller that predates this parameter keeps the namespace it always had.
if(NOT DEFINED NAMESPACE)
    set(NAMESPACE "azo::rhi::utils::shaders")
endif()

file(READ "${IN}" _hex HEX)
string(LENGTH "${_hex}" _hexLength)
math(EXPR _byteCount "${_hexLength} / 2")

if(_byteCount EQUAL 0)
    message(FATAL_ERROR "azoth_rhi_embed_shader: ${IN} is empty, so the compile produced no bytecode.")
endif()

# Two hex digits per byte, wrapped so the generated header stays readable in a diff and does not run to one
# enormous line that some editors refuse to open.
string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
string(REGEX REPLACE "(([^,]+,){12})" "\\1\n\t" _bytes "${_bytes}")

# A bare semicolon is a list separator to CMake, so the one the generated C++ needs is carried in a variable.
string(ASCII 59 _semicolon)

set(_content "// Generated by cmake/azoth_rhi_embed_shader.cmake. Do not edit: rebuild instead.\n")
string(APPEND _content "// Source: ${IN}\n\n#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n")
string(APPEND _content "namespace ${NAMESPACE}\n{\n")
string(APPEND _content "\tinline constexpr std::uint8_t ${SYMBOL}[] = {\n\t${_bytes}\n\t}${_semicolon}\n\n")
string(APPEND _content "\tinline constexpr std::size_t ${SYMBOL}Size = ${_byteCount}${_semicolon}\n")
string(APPEND _content "} // namespace ${NAMESPACE}\n")

# Written through a compare so an unchanged shader does not restamp the header and rebuild everything that
# includes it.
file(WRITE "${OUT}.tmp" "${_content}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT}.tmp" "${OUT}")
file(REMOVE "${OUT}.tmp")
